version: '3.2'
services:
  rabbit-on-rails:
    build:
      context: ./rabbit-on-rails
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "ruby", "listener.rb"]
    volumes:
      - ./rabbit-on-rails:/rabbit-on-rails
      - type: tmpfs
        target: /rabbit-on-rails/tmp/pids/
    ports:
      - "3001:80"
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
